---

- hosts: all
  become: true
  tasks:

  - name: Stop Apache Webserver
    service:
      name: httpd
      state: stopped
  - name: Remove Apache Webserver
    yum:
      name: httpd
      state: absent
